### ISSUE TITLE
Incompetence?

### ISSUE THREAD

**Issue by Subash-Chandra** [black-forest-labs/flux#4]
Who decided to put 'cd $HOME' in the local installation commands?

And no requirements.txt? I have to use a -e '[.all]'??? wtf is that?

Why not just be normal, and provide instructions that work like literally every other Python  program on the planet?

**Comment by JonasLoos** [comment]
You could just ignore `cd $HOME` if you don't want to have it in your home dir but somewhere else.

`-e` stands for editable mode and `.[all]` for installing the package in the current directory with all dependencies (which are listed in `pyproject.toml`).

I guess they might provide the code like this, because it allows for easy importing of the code and so that it can be run by just typing `flux`. This is actually not too uncommon.
