### ISSUE TITLE
Questions about 'guidance_embeds' and 'guidance_scale' used in flux-dev and flux-schnell

### ISSUE THREAD

**Issue by ewrfcas** [black-forest-labs/flux#63]
I am confused about the settings of 'guidance_embeds' and 'guidance_scale' in flux-dev and flux-schnell.
flux-dev contains ```"guidance_embeds": true```, while flux-schenell contains ```"guidance_embeds": false```.
I have not found any related work to introduce guidance_embeds. It is different from the classifier-free-guidance (CFG) used in previous T2I works.
If I want to fine-tune flux-dev, how can I get guidance_scale, which is regarded as the input to the transformer embedding?
Why flux-schenell set guidance_embeds to false? How to use CFG for flux-schenell?

**Comment by JonasLoos** [comment]
If I understand correctly, flux-schnell doesn't CFG, while flux-dev does. Similarly, [SDXL-Turbo](https://huggingface.co/stabilityai/sdxl-turbo) also doesn't use CFG, while the base SDXL does.

I guess "guidance_embeds" is just to control whether or not embeddings for CFG are passed to the model or not.

In the [huggingface implementation for flux-dev](https://huggingface.co/black-forest-labs/FLUX.1-dev), they suggest a guidance_scale of 3.5. 
For flux-schnell it's 0.0, i.e. disabled.

**Comment by ewrfcas** [comment]
Thanks. I guess that schnell is distilled with a fixed guidance score (maybe 3.5), so guidance_embeds is discarded here.

**Comment by Oguzhanercan** [comment]
"in one-shot scenarios, CFG simply oversaturates samples rather than improving text-alignment. This observation suggests that CFG works best in settings with multiple steps, allowing for corrections of oversaturation issues ins most case." Probably schnell is distilled to one step, so they do not use cfg.

 
![image](https://github.com/user-attachments/assets/19cc5636-38e6-4baf-8572-7b44e3a1619d)
